### ISSUE TITLE
Production minification and fingerprinting.

### ISSUE THREAD

**Issue by matthewlehner** [matthewlehner/phoenix-webpack-example#2]
Webpack should minify and fingerprint CSS/JS for a production build.

- [ ] Minify assets
- [ ] Fingerprint assets

**Comment by Blackrush** [comment]
Isn't `mix phoenix.digest` doing fingerprints/gzip ?

**Comment by matthewlehner** [comment]
Closed by ba8bc5cce81cda0047eec5c95c5e4096aa489997
